repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        description: Code reformatting
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8
        description: Checking code base against PEP8
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: isort
        description: Sorting imports
        language: system
        types: [python]
        args: ["--profile=black"]
    -   id: mypy
        name: mypy
        entry: mypy
        description: Static type checker for Python
        language: system
        types: [python]
        args: [--no-strict-optional, --ignore-missing-imports]
