name: face_distance_investigation
dependencies:
- python==3.12
- pillow==11.2.1
- scipy==1.15.2
- pandas==2.3.0
- pip:
    - face_recognition==1.3.0
    - opencv-python==4.11.0.86
    - matplotlib==3.10.3
    - numpy==2.1.3
    - scikit-learn==1.7.0
    - wordcloud==1.9.4
    - pre-commit==4.2.0
    - flake8==7.2.0
    - isort==6.0.1
    - mypy==1.16.0
    - black==25.1.0
    - tqdm==4.67.1
    - tensorboard==2.19.0
    - tensorflow==2.19.0