name: face_distance_investigation
dependencies:
- python==3.5.2
- pillow==5.3.0
- scipy == 0.18.0
- pandas==0.23.4
- pip:
    - face_recognition==1.2.3
    - opencv-python==3.4.4.19
    - matplotlib==3.0.2
    - numpy==1.16.0
    - scikit-learn==0.20
    - wordcloud==1.5.0